Iter5
ilegorro/almetrics pull request #5
Opened 2023-08-03 15:38 UTC by ilegorro

2023-08-04 16:40 UTC, popoffvg requested changes

2023-08-04 16:40 UTC, popoffvg commented on cmd/server/main.go
> +	if err != nil {
[major]
Стандартный сервер возвращает ошибку `ErrServerClosed` при штатном завершении работы. Её стоит обрабатывать с помощью `errors.Is`

2023-08-04 16:40 UTC, popoffvg commented on cmd/server/main.go
> +		panic(err)
[minor]
Лучше не кидать панику, т.к. в общем случае в сервисе может быть несколько компанент. Например, кафка и http-server и нужно будет завершать все компоненты аккуратно с флешом кешей. 

Лучше возвращать ошибку и обрабатывать её на верхнем уровне

2023-08-04 16:40 UTC, popoffvg commented on cmd/server/main_test.go
> +	defer resp.Body.Close()
[major]
Тело нужно закрывать только в одном месте. Если resp или body возвращается из функции закрывать её ни в коем случае не следует, т.к. оно может быть другой разработчик может попытаться его прочитать и получит неожиданный результат. 

Также если тело уже прочитано, то повторно прочитать его нельзя.
Следует для маленького payload вычитывать тело в буфер и создавать на его основе reader, для больших файлов испльзовать пакет io (TeeReader, Pipe)

2023-08-04 16:40 UTC, popoffvg commented on internal/agent/metrics.go
> +		resp, err := http.Post(requestURL, "text/plain", nil)
[minor]

К сожалению, пакет context будет дальше по курсу, но важно отметить работу с запросами сразу. 

Не стоит использовать запросы без контекста, т.к. в случае недоступности сервиса горутины будут вечно ожидать ответа, что приведет к росту потребления оперативной памяти и в конечном счете падению приложения.

```go
// псевдокод
ctx = context.WithTimeout(context.Background())
req := http.NewRequestWithContext(ctx)
http.DefaultClient.Do(req)
```

2023-08-04 16:40 UTC, popoffvg commented on cmd/server/main_test.go
> +package main
[minor]

Лучше тесты в пакете main не писать, а писать в папке test или в пакетах с реально проверяемым кодом. В данном случае в пакете с сервером.

2023-08-04 16:40 UTC, popoffvg commented on internal/agent/flags.go
> +	parts := strings.Split(s, ":")
[minor]

Лучше использовать `url.Parse`

2023-08-04 16:40 UTC, popoffvg commented on internal/agent/flags.go
> +	return
[major]

Надо стараться избегать возврата без указания возвращаемых значений, т.к. при изменении кода это может привести к ошибкам.

2023-08-04 16:40 UTC, popoffvg commented on internal/agent/flags.go
> +	op := &Options{
[minor]

У carl0s/env есть возвможность указать значения по умолчанию через тег `envDefault`

2023-08-04 16:40 UTC, popoffvg commented on internal/agent/metrics_test.go
> +			m.Report(srv.URL)
[minor]

Не ипользуется want

2023-08-04 16:40 UTC, popoffvg commented on internal/handlers/get.go
> +	respHTML := `<html>
[minor]

Для генерации статическго html лучше использовать template/html из-за встроенного эскейпинга символов.

2023-08-04 16:40 UTC, popoffvg commented on internal/handlers/get.go
> +		v, ok := ctx.strg.GetGauge(mName)
[minor]

Для всех интерфейсов, которые предпалагают хранение данных в сигнатуру всегда лучше добавлять `context.Context` и возвращать ошибку, т.к. скорее всего storage будет меняться с мемори рано или поздно или потребуется управление жизнью запроса.

2023-08-04 16:40 UTC, popoffvg commented on internal/handlers/get.go
> +		v, ok := ctx.strg.GetGauge(mName)
[major]

ctx - лучше использовать только для пакета context.Context.

2023-08-04 16:40 UTC, popoffvg commented on internal/storage/memstorage.go
> +	m.gauge[name] = value
[major]

Тут мьютексы намного больше чем в клиенте, т.к. тут возможна || запись, что может привести к панике.

2023-08-04 16:40 UTC, popoffvg commented on internal/storage/memstorage.go
> +	res := make(map[string]string)
[minor]

для мапы можно указать размер сразу

2023-08-04 16:40 UTC, popoffvg commented on internal/storage/memstorage.go
> +func (m MemStorage) GetMetrics() map[string]string {
[major]

Методы с ресивером не указателем требуют обоснования, т.к. это всегда лишние аллокации памяти

2023-08-04 16:41 UTC, popoffvg commented
[minor] - необязательно к исправлению
[major] - обязательно к исправлению

2023-08-07 11:05 UTC, ilegorro commented on internal/agent/flags.go
> +	op := &Options{
В данном случае если указать значения по умолчанию в описании переменных окружения, то нарушится условие задачи по приоритетности параметров. Мы получим значение по умолчанию в случае отсутствия переменной окружения и будет непонятно, задана переменная или нет, а значит, будет непонятно, надо ли брать значение параметра из флага.

2023-08-08 16:04 UTC, ilegorro commented on internal/agent/metrics.go
> +		resp, err := http.Post(requestURL, "text/plain", nil)
Пока не стал добавлять контекст, не настолько хорошо удалось разобраться самостоятельно

2023-08-08 16:07 UTC, ilegorro commented on internal/storage/memstorage.go
> +	res := make(map[string]string)
Насколько я понимаю, в таком случае нужно отдельно задавать списки характеристик и размер мапы устанавливать по размерам этих списков. Я пока не разобрался, как у runtime.ReadMemStats получать значения по ключу, поэтому списки решил пока не добавлять

2023-08-09 13:35 UTC, popoffvg commented on internal/storage/memstorage.go
> +	res := make(map[string]string)
Нет. size := len(m.gauge) + len(m.counter)

2023-08-09 13:39 UTC, popoffvg approved these changes

2023-08-09 16:46 UTC, merged