Iter8
ilegorro/almetrics pull request #8
Opened 2023-08-21 09:37 UTC by ilegorro

2023-08-22 20:02 UTC, popoffvg requested changes

2023-08-22 20:02 UTC, popoffvg commented on internal/middleware/compression.go
> +			cr, err := newCompressReader(r.Body)
[major]
Тело нужно закрывать

2023-08-22 20:02 UTC, popoffvg commented on internal/middleware/compression.go
> +func newCompressReader(r io.ReadCloser) (*compressReader, error) {
[major]

Не закрываешь тут тело, а в качестве интерфейса выбран io.ReadCloser. 
Если Reader не закрывается следует использовать io.Reader

2023-08-24 09:20 UTC, ilegorro commented on internal/middleware/compression.go
> +func newCompressReader(r io.ReadCloser) (*compressReader, error) {
Ридер закрывается отдельным методом, который реализован ниже по коду.
`
func (c *compressReader) Close() error {
	if err := c.r.Close(); err != nil {
		return err
	}
	return c.zr.Close()
}
`
По остальным замечаниям все поправил.

2023-08-29 05:20 UTC, merged